package com.scienceminer.glutton.command;

import com.scienceminer.glutton.configuration.LookupConfiguration;
import com.scienceminer.glutton.matching.*;
import io.dropwizard.core.cli.ConfiguredCommand;
import io.dropwizard.core.setup.Bootstrap;
import net.sourceforge.argparse4j.inf.Namespace;
import net.sourceforge.argparse4j.inf.Subparser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.util.*;

/**
 * Evaluate matching strategies on held-out test data.
 * Reads a CSV file (same format as generated by GenerateTrainingDataCommand)
 * and reports precision, recall, F1 at multiple thresholds for each strategy.
 */
public class EvaluateMatchingCommand extends ConfiguredCommand<LookupConfiguration> {
    private static final Logger LOGGER = LoggerFactory.getLogger(EvaluateMatchingCommand.class);

    private static final String ARG_INPUT = "input";
    private static final double[] THRESHOLDS = {0.5, 0.7, 0.9};

    public EvaluateMatchingCommand() {
        super("evaluate_matching", "Evaluate matching strategies on test data");
    }

    @Override
    public void configure(Subparser subparser) {
        super.configure(subparser);

        subparser.addArgument("--input")
                .dest(ARG_INPUT)
                .type(String.class)
                .required(true)
                .help("Path to test CSV file (same format as training data)");
    }

    @Override
    protected void run(Bootstrap bootstrap, Namespace namespace, LookupConfiguration configuration) throws Exception {
        String inputPath = namespace.getString(ARG_INPUT);
        LOGGER.info("Evaluating matching strategies on: {}", inputPath);

        // Load test data
        List<TestSample> testData = loadTestData(inputPath);
        LOGGER.info("Loaded {} test samples", testData.size());

        // Determine model path from configuration
        LookupConfiguration.Matching matchingConfig = configuration.getMatching();
        String modelPath = (matchingConfig != null) ? matchingConfig.getModelPath() : "data/models";

        // Initialize strategies
        Map<String, MatchingStrategy> strategies = new LinkedHashMap<>();
        strategies.put("simple_average", new SimpleAverageStrategy());

        LogisticRegressionStrategy logreg = new LogisticRegressionStrategy();
        try {
            logreg.initialize(modelPath);
            strategies.put("logistic_regression", logreg);
        } catch (IOException e) {
            LOGGER.info("Logistic regression model not available: {}", e.getMessage());
        }

        XGBoostStrategy xgboost = new XGBoostStrategy();
        try {
            xgboost.initialize(modelPath);
            strategies.put("xgboost", xgboost);
        } catch (IOException e) {
            LOGGER.info("XGBoost model not available: {}", e.getMessage());
        }

        NeuralStrategy neural = new NeuralStrategy();
        try {
            neural.initialize(modelPath);
            strategies.put("neural", neural);
        } catch (IOException e) {
            LOGGER.info("Neural model not available: {}", e.getMessage());
        }

        // Initialize simple_average (no-op but for consistency)
        strategies.get("simple_average").initialize(modelPath);

        // Evaluate each strategy
        System.out.println();
        System.out.println("=== Matching Strategy Evaluation ===");
        System.out.println("Test samples: " + testData.size());
        System.out.println();

        // Print header
        System.out.printf("%-25s", "Strategy");
        for (double t : THRESHOLDS) {
            System.out.printf("| Threshold=%.1f              ", t);
        }
        System.out.println();

        System.out.printf("%-25s", "");
        for (double t : THRESHOLDS) {
            System.out.printf("| %-8s %-8s %-8s ", "Prec", "Recall", "F1");
        }
        System.out.println();
        System.out.println("-".repeat(25 + THRESHOLDS.length * 30));

        for (Map.Entry<String, MatchingStrategy> entry : strategies.entrySet()) {
            String name = entry.getKey();
            MatchingStrategy strategy = entry.getValue();

            // Score all test samples
            double[] scores = new double[testData.size()];
            for (int i = 0; i < testData.size(); i++) {
                scores[i] = strategy.score(testData.get(i).features);
            }

            System.out.printf("%-25s", name);

            for (double threshold : THRESHOLDS) {
                int tp = 0, fp = 0, fn = 0, tn = 0;
                for (int i = 0; i < testData.size(); i++) {
                    boolean predicted = scores[i] >= threshold;
                    boolean actual = testData.get(i).label == 1;
                    if (predicted && actual) tp++;
                    else if (predicted && !actual) fp++;
                    else if (!predicted && actual) fn++;
                    else tn++;
                }

                double precision = (tp + fp > 0) ? (double) tp / (tp + fp) : 0.0;
                double recall = (tp + fn > 0) ? (double) tp / (tp + fn) : 0.0;
                double f1 = (precision + recall > 0) ? 2 * precision * recall / (precision + recall) : 0.0;

                System.out.printf("| %-8.4f %-8.4f %-8.4f ", precision, recall, f1);
            }
            System.out.println();
        }

        System.out.println();
        LOGGER.info("Evaluation complete");
    }

    private List<TestSample> loadTestData(String path) throws IOException {
        List<TestSample> samples = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
            String header = reader.readLine(); // skip header
            if (header == null) {
                throw new IOException("Empty test data file");
            }

            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;

                String[] parts = line.split(",", -1);
                if (parts.length != MatchingFeatures.NUM_FEATURES + 1) {
                    LOGGER.debug("Skipping malformed line: {}", line);
                    continue;
                }

                double[] features = new double[MatchingFeatures.NUM_FEATURES];
                boolean[] present = new boolean[MatchingFeatures.NUM_FEATURES];

                for (int i = 0; i < MatchingFeatures.NUM_FEATURES; i++) {
                    if (parts[i].isEmpty()) {
                        features[i] = 0.0;
                        present[i] = false;
                    } else {
                        features[i] = Double.parseDouble(parts[i]);
                        present[i] = true;
                    }
                }

                int label = Integer.parseInt(parts[MatchingFeatures.NUM_FEATURES]);
                samples.add(new TestSample(new MatchingFeatures(features, present), label));
            }
        }
        return samples;
    }

    private static class TestSample {
        final MatchingFeatures features;
        final int label;

        TestSample(MatchingFeatures features, int label) {
            this.features = features;
            this.label = label;
        }
    }
}
